# Generated by Django 2.2.5 on 2019-09-28 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=20)),
                ('fees', models.IntegerField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trainers.TrainerModel')),
            ],
        ),
    ]
