# Generated by Django 2.2.5 on 2019-09-30 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batchapp', '0002_batch_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.CourseModel'),
        ),
    ]
