# Generated by Django 2.2.5 on 2019-10-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_trainermodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainermodel',
            name='description',
        ),
        migrations.AddField(
            model_name='trainermodel',
            name='experience',
            field=models.TextField(default='blah'),
        ),
    ]
