# Generated by Django 2.2.5 on 2019-10-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_auto_20191005_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainermodel',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
