# Generated by Django 2.2.5 on 2019-10-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_auto_20191021_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainermodel',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='photos'),
        ),
    ]
